language: node_js
node_js:
- 10
before_script:
- npm install -g gulp-cli gulp@4
script:
- gulp
- npm run coverage
cache:
  directories:
  - node_modules
env:
  global:
    secure: jGMC6vnV80nLMNv7RZ+oZNRIb4edY3uY8NH6VV/PQp00uLo08xwOYYlgvDiuYvxRPRoU35Nwh0PJAOk2m2Jrq5miBLh7VinIdXva+hcRgCBycAaIw8tLQqu9/7wOTqqpbxQENxllPB2gdvWLKgJ6o9JwofbQVHLxRkh9iM0salPH1uF5N5WecHkxkiwXp4ySy1Uo78by+VUzjoH+29BDwumrnuBkUQ31A8wogI2dhAzGcw8hVcPkdobeEoyOqI12+POPDeurctA0pTSn8pgtsudPaWeVPjN4J0yQ8PAfE6Gue1hlHG/o1tMxMgtjo9ScVLH2MolYcTRxwP6R3ffbHjUzvaUkdvwn+iQVokNxshKd4S4jOV++U6puTqMnqunHnNRZhf4Lx39KXb/fS9BsoufmrNoYtidKceinuYjwkrB4VURUwrt9jfL2hWZ8uty9ixN5qAnuhHgK+k2Ff3cfNEyFmsGjyiaIN6cRgQzbc2MeGWqBHg+/eFvg8aRCmvtS3YWCpLlZWzGXlllBRYx0aUvmNsg/aOpYCuybz/po7ebNHYdEHD2xqVtSYc+S7NYGpta6k228PGNCEkDcklpJtl/2hdvaORpOWvGs/O2Wk614VboFm5Vk3no0f1lKuuCoOzW5LkBLgg0/tyV94vUlCJsMb4J/4ep1XQGbiUJdcGs=
notifications:
  slack:
    secure: S3JlaPxVCNAxQiQ1LT7KjnhYSbZHs4APW/Zzfg7nZvTpA0kCBv7/ffHJmfjAvhiNjU4/BcMdC4I7k2ERm2/KM/hgQ3R4b+pgpgWX1L89gBgBb6/L0MkJA6i+5cbYqZ+xLOQCHPj6cVmhKf7hHoHxBehtX6g12YIftz08xsNesNQpSFkcPJSWceIgCjixoyRZxNk9tctebg5qgfQaj+AYTLzO1y0p51MKfuXbG2edjb79jW0s9DdaPfNYQ7Fy8w9WoOwuvD5Yd8HROaWwua9ZVMjCRHk0AYnZHFagIAGGIgDnpZWIdfn/hDP+fAhopqLrHLknpk+ZBuUXbk09gJLkFowONVEaxsi258iBCAapsQYRJnx1WeRyWa7jpwxQJ84Zu84vGa7cfij5C2MEo7SmOBqLSyW5X9nFiQNcJfYBcWhp3WreG5G0wT3DZEZVwiU0uatXoHJ5kOJYFZQ1eevFVS3/f7Fi1HyjT2KteAe4cJA88ND4yYewmbx5Fl0BC0SjfmB1K27iMFpZ0UkPzV0qt+JehUfDB1cPMCQcU0nACZtWWCeC1Urf23pw1v27eHfSaJ58TQ8Lj2tDySLL9k+mKabghkJBQedgY8X0e9ZSv+CKuSDOSzyU5cyKHOsziZQnZGqRpLmc71yUnx+kToFdvlRNP6vZ+9oeJrazLt2N4+Q=
