language: node_js
node_js:
- 10
before_script:
- npm install -g gulp-cli gulp@4
script:
- gulp
- npm run coverage
cache:
  directories:
  - node_modules
env:
  global:
    secure: XWhLnuw9ngQ1KlH+5ScVWolLvcAxqC/ep0BPbj0anhtGJKDy6guBPqTmJnSeN0X5kAyFmXn7iwDy5NJTyXCuik8hZCNLj8j5bTPIA9sp+tPhlUvJuM4hj7IJPYsp7R1dSvlWdFa33AiX5CiSML7w1Majgphqih3P2cInwNVKbf5n3qdyNgnGkgqFOJU3AaTHQuryuaDjfHh9iapFYHFXUAcWe/BYSW6HDtTDUaeI5y5AHHVyLFJEeikwSOCdsb5jwrysuDQXafeX1E/MXpsSjF+3J1XIGFnw1nTPWUsLjikT8c4DuGBXWFGfEmgI4SFtFyp1HjtSfNLG9BExkcOmxLEnGtDuIMiLcSLFGQsPkTCQVTWPTrJFbVaHfZ+k6oGrgktf8iIVQ31A1+knoC6CGaZ+7oUUaLd8hdrMXBg2IuStCEyKNcqNqgf65VLBOvYnrW0FQg8OFf1y8PT2acG7NrqQXOBS+iSvxHo2FZJV/OaYRTFqhDtwSmqptcQmFGi6L0xuns3piMv2rd07ozvhtQS8AFvDOEs56YD0fbbCKFntf7jOlsOm3QAffB60qtJIDs5SMFc79rknw3rSuPa9jxVQzXKp4txpim14O9+WBOd9BZRXVdw3cmOXpijzhgbqOZ7D5TUzADFRx7oiIGF4LTDddhm8n11Cs3qWvkYIMY4=
notifications:
  slack:
    secure: SVrhQOLS32tKIbNPJNbkJjF6zALUE4Qxv94xIx7EHH6obZX+0YB3SZEgRdyhZHsvBnDjQZQUDvdGvs2WNiqAicMQ6NPw9PHSCG+h5JBtg+zBEG7cd5U2giJfH0QwfKicXEqQOA4pHtRE7nyiUe6O4gCGRuC5iURtNXSE42K1jpzBwDP1CzoMvizfqJ8HtT6GiewHJ5KSI9KTqeusIrcYeIiwBi9l6qMNqA1KRu3L2T3YM1e55M1xWjCu13fWML51FjAt4A6XXZIpUs/8fPmOWKl0pyK9rqFPGeItU3rXlG913XlkCCGa1FQIZTKPXlldTwCCy9Z8DoZqPr95S1+4LI5M82YdMoYb7zk67T8R0fNrK7ldcFacgrAsnyHX0M73ysdC9zD8DjvpyFfn9v+JPwZMPtbdLF5hCpx/Y6jflBeSlf0yVSEmZokbGXcFIIf5ncPs5XBdKKn8PTWScE858LCYTO50Lh9JQtfI8vmamYiyopQ+tNlC6p7pnvieY8dR1Ojg3n9kDgWpslWOBsuy+ojcjjvXGr3VUYGvJwSiRgCvfzDKnej+5kxvAqQEnEAjal4QNpMlM1qSV4MLLYRUwii5gq2oRmR6UKuIumnOf/8t7t/+kQpXcgJ1p44GgZf6GhIRBCP/nMMeqnQuTj13ljcnHG+oc4C6/HMctgMPWx8=
